import { useEffect, useState } from 'react';
import { api } from '../utils/api';
import ButtonCard from '../components/ButtonCard.jsx';

export default function Home() {
  const [buttons, setButtons] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.latest()
      .then((d) => setButtons(d.buttons))
      .catch(() => setButtons([]))
      .finally(() => setLoading(false));
  }, []);

  return (
    <>
      <section className="text-center mb-12">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-white/10 bg-white/5 text-xs font-semibold mb-4 text-fuchsia-300">
          <span className="w-1.5 h-1.5 rounded-full bg-fuchsia-400 animate-pulse"></span>
          Fresh batch · {new Date().toLocaleDateString(undefined, { dateStyle: 'medium' })}
        </div>
        <h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight leading-tight">
          25 new animated buttons,
          <span className="block bg-gradient-to-r from-indigo-400 via-fuchsia-400 to-pink-400 bg-clip-text text-transparent animate-gradient-x bg-[length:200%_200%]">
            generated by AI every day.
          </span>
        </h1>
        <p className="mt-5 max-w-2xl mx-auto text-slate-400">
          Browse today's collection, like your favorites, and stash them in a
          flip-card cart that shows the full source code on the back.
        </p>
      </section>

      {loading ? (
        <Skeleton />
      ) : buttons.length === 0 ? (
        <Empty />
      ) : (
        <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
          {buttons.map((b) => (
            <ButtonCard key={b._id} button={b} />
          ))}
        </section>
      )}
    </>
  );
}

function Skeleton() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
      {Array.from({ length: 8 }).map((_, i) => (
        <div key={i} className="glass h-56 animate-pulse" />
      ))}
    </div>
  );
}

function Empty() {
  return (
    <div className="glass p-12 text-center">
      <p className="text-2xl font-bold mb-2">No buttons yet</p>
      <p className="text-slate-400">
        Run the seed script or trigger the daily generator to populate the gallery.
      </p>
    </div>
  );
}
